[build]
builder = "NIXPACKS"

[deploy]
startCommand = "pnpm start:prod"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"
DB_TYPE = "mysql"
DB_SYNCHRONIZE = "true"
DB_LOGGING = "false"
DB_CHARSET = "utf8mb4"
DB_TIMEZONE = "+00:00"
