[build]
builder = "NIXPACKS"

[deploy]
buildCommand = "pnpm install && pnpm build"
startCommand = "pnpm init-db && pnpm railway:start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
# 基础配置
NODE_ENV = "production"
PORT = "3000"
HOST = "0.0.0.0"

# JWT 配置
JWT_SECRET = "interview_jwt_secret_key_a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6"
JWT_EXPIRES_IN = "24h"

# Railway MySQL 数据库配置
DB_TYPE = "mysql"
DB_HOST = "gondola.proxy.rlwy.net"
DB_PORT = "39395"
DB_USERNAME = "root"
DB_PASSWORD = "aspFqYqTuBJyeNrfTDKcRAKuYBEuQyeB"
DB_DATABASE = "railway"
DB_SSL = "true"
DB_SYNCHRONIZE = "true"
DB_LOGGING = "false"
DB_CHARSET = "utf8mb4"
DB_TIMEZONE = "+08:00"
DB_CONNECTION_LIMIT = "10"

# CORS 配置
CORS_ORIGINS = "*"

# WebSocket 配置
WS_PORT = "1234"
WS_HOST = "0.0.0.0"

# 功能配置
ENABLE_REGISTRATION = "false"
MAX_ROOM_MEMBERS = "10"
ROOM_CODE_LENGTH = "6"
AUTO_SAVE_INTERVAL = "3000"

# 管理员账户配置
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "admin123456"
ADMIN_EMAIL = "admin@example.com"