[build]
builder = "NIXPACKS"

[deploy]
buildCommand = "pnpm install && pnpm build"
startCommand = "pnpm railway:start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
# 设置生产环境标识
NODE_ENV = "production"